//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_reviews
    {
        public int ID { get; set; }
        public Nullable<int> Product_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Comment { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
